### ISSUE TITLE
Is it still being maintained and updated?

### ISSUE THREAD

**Issue by qcjxberin** [undergroundwires/SafeOrbit#19]
Is it still being maintained and updated?

**Comment by undergroundwires** [comment]
I'll keep the long-term support for bug fixes, security improvements and performance optimizations. I use it for some private projects including a password manager (not open-sourced) without any issues. If there's any bugs or issues I'm ready to take a look at them. As I depend on this library for my private projects.

It's a hobby project so development will be slow from my side when I have time. I see it as a stable and well-tested project as it is now. I don't plan to build any new features at all, but would accept well-tested community PRs. But bugs and performance issues will be fixed.

My future roadmap is to publish better documentation online. Otherwise, I watch homomorphic encryption development closely and projects like [SEAL](https://github.com/microsoft/SEAL) and it would be nice to change encryption behind the scenes to that technology.
